(() => {
 const c=window.tractatusSupabaseClient;
 const tabs=[...document.querySelectorAll('.discussion-tab')], panel=document.getElementById('discussion-propositions'), general=document.getElementById('discussion-general'), form=document.getElementById('discussion-proposition-form'), input=document.getElementById('discussion-proposition-number'), result=document.getElementById('discussion-proposition-result'), recent=document.getElementById('discussion-recent-list');
 document.getElementById('discussion-auth')?.remove(); if(!c||!form||!result)return;
 let num=null,disc=null;
 const e=v=>String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;');
 const dt=v=>v?new Intl.DateTimeFormat('uk-UA',{day:'numeric',month:'long',year:'numeric'}).format(new Date(v)):'';
 const pf=(p='')=>`<form class="discussion-comment-form" data-parent-id="${e(p)}"><label>Ваше ім’я</label><input class="discussion-author-name" required maxlength="80" value="${e(localStorage.getItem('tractatus-discussion-name')||'')}"><label>E-mail</label><input class="discussion-author-email" type="email" required maxlength="254" value="${e(localStorage.getItem('tractatus-discussion-email')||'')}" placeholder="Не публікується"><label>Коментар</label><textarea class="discussion-comment-body" rows="5" required maxlength="10000"></textarea><button type="submit">Надіслати</button><p class="discussion-form-note">Реєстрація не потрібна. E-mail не показується в обговоренні.</p></form>`;
 tabs.forEach(t=>t.addEventListener('click',()=>{let a=t.dataset.discussionTab==='propositions';tabs.forEach(x=>x.classList.toggle('active',x===t));panel.hidden=!a;general.hidden=a;}));
 async function gd(n){let {data,error}=await c.from('discussions').select('id,proposition_number,title,created_at').eq('kind','proposition').eq('proposition_number',n).maybeSingle();if(error)throw error;return data}
 async function ed(n){let d=await gd(n);if(d)return d;let r=await c.from('discussions').insert({kind:'proposition',proposition_number:n,title:`Обговорення положення ${n}`}).select('id,proposition_number,title,created_at').single();if(!r.error)return r.data;d=await gd(n);if(d)return d;throw r.error}
 function posts(ps){let m=new Map;ps.forEach(p=>{let k=p.parent_id==null?'r':String(p.parent_id);if(!m.has(k))m.set(k,[]);m.get(k).push(p)});let lv=(k,r=false)=>(m.get(k)||[]).map(p=>`<article class="discussion-post${r?' discussion-reply':''}"><div class="discussion-post-meta"><strong>${e(p.author_name)}</strong><span>${e(dt(p.created_at))}</span></div><p>${e(p.body).replaceAll('\n','<br>')}</p><button class="discussion-reply-action" data-reply-id="${p.id}" type="button">Відповісти</button>${lv(String(p.id),true)}</article>`).join('');return lv('r')}
 async function open(n,s=true){num=n;disc=null;result.innerHTML='<p class="discussion-placeholder">Відкриваю обговорення…</p>';try{disc=await gd(n);if(!disc)result.innerHTML=`<div class="discussion-proposition-card"><p class="discussion-proposition-number">${e(n)}</p></div><p class="discussion-placeholder">Обговорення цього положення ще не розпочато.</p>${pf()}`;else{let r=await c.from('posts').select('id,parent_id,author_name,body,created_at').eq('discussion_id',disc.id).order('created_at',{ascending:true});if(r.error)throw r.error;result.innerHTML=`<div class="discussion-proposition-card"><p class="discussion-proposition-number">${e(n)}</p><div class="discussion-proposition-text">${e(disc.title)}</div></div>${r.data.length?`<div class="discussion-thread">${posts(r.data)}</div>`:'<p class="discussion-placeholder">У цьому обговоренні ще немає дописів.</p>'}${pf()}`}bind();if(s)result.scrollIntoView({behavior:'smooth',block:'start'})}catch(x){result.innerHTML=`<p class="discussion-placeholder">Не вдалося завантажити обговорення: ${e(x.message)}</p>`}}
 function bind(){result.querySelectorAll('.discussion-comment-form').forEach(f=>f.addEventListener('submit',async q=>{q.preventDefault();let name=f.querySelector('.discussion-author-name').value.trim(),email=f.querySelector('.discussion-author-email').value.trim(),body=f.querySelector('.discussion-comment-body').value.trim(),note=f.querySelector('.discussion-form-note');if(!name||!email||!body)return;note.textContent='Надсилаю…';localStorage.setItem('tractatus-discussion-name',name);localStorage.setItem('tractatus-discussion-email',email);try{let d=disc||await ed(num),p=f.dataset.parentId,r=await c.from('posts').insert({discussion_id:d.id,parent_id:p?Number(p):null,author_name:name,author_email:email,body});if(r.error)throw r.error;await open(num,false);await rr()}catch(x){note.textContent=`Не вдалося додати допис: ${x.message}`}}));result.querySelectorAll('.discussion-reply-action').forEach(b=>b.addEventListener('click',()=>{result.querySelectorAll('.discussion-inline-reply').forEach(x=>x.remove());let h=document.createElement('div');h.className='discussion-inline-reply';h.innerHTML=pf(b.dataset.replyId);b.after(h);bind();h.querySelector('textarea')?.focus()}))}
 form.addEventListener('submit',q=>{q.preventDefault();let n=input.value.trim().replace(',','.');if(n)open(n)});
 async function rr(){if(!recent)return;try{let r=await c.from('discussions').select('id,proposition_number,title,created_at').eq('kind','proposition').order('created_at',{ascending:false}).limit(20);if(r.error)throw r.error;let a=await Promise.all(r.data.map(async d=>{let p=await c.from('posts').select('id,created_at').eq('discussion_id',d.id).order('created_at',{ascending:false});if(p.error)throw p.error;return{...d,count:p.data.length,last:p.data[0]?.created_at||d.created_at}}));a.sort((x,y)=>new Date(y.last)-new Date(x.last));recent.innerHTML=a.length?a.map(d=>`<button class="discussion-recent-item" type="button" data-proposition="${e(d.proposition_number)}"><span class="discussion-recent-title"><strong>${e(d.proposition_number)}</strong> — ${e(d.title)}</span><span class="discussion-recent-meta">${d.count} дописів · останній ${e(dt(d.last))}</span></button>`).join(''):'<p class="discussion-placeholder">Поки що обговорень немає.</p>';recent.querySelectorAll('.discussion-recent-item').forEach(b=>b.addEventListener('click',()=>{input.value=b.dataset.proposition;tabs[0]?.click();open(b.dataset.proposition)}))}catch(x){recent.innerHTML=`<p class="discussion-placeholder">Не вдалося завантажити останні обговорення: ${e(x.message)}</p>`}}
 rr();
})();